version: '3.1'
volumes:
  mongo_data:
services:
  server:
    restart: unless-stopped
    image: server:latest
    environment:
      MONGO_HOST: localhost
      DB_NAME: company
    ports:
      - 4000:4000
    volumes:
      - ./server:/user/src/app
    links:
      - mongo
    command: npm start
    tty: true
    stdin_open: true

  mongo:
    restart: unless-stopped
    image: mongo:3.6.4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017